name: handwritten_digit_classifier
description: An application to classify handwritten digits
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  camera: ^0.4.2
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  image: ^2.0.7
  path_provider: ^0.5.0
  tflite: ^1.0.1

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/model/
    - assets/launcher/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher/icon_hwd.png"